spring.application.name=git-master

server.port=8091

# 这是 Spring Boot 的一个默认配置（OSIV）。
# 它为了开发方便，允许在视图层（比如 HTML 模板）也能查询数据库。
# 但在大型项目中，这可能会导致性能问题或连接池枯竭。
spring.jpa.open-in-view=false

# 数据库连接 URL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=8e89cfaaa

# 驱动类名
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate 配置
# update 表示自动根据 Java 实体类同步数据库表结构（开发环境常用）
spring.jpa.hibernate.ddl-auto=update
# 在控制台打印 SQL 语句，方便调试
spring.jpa.show-sql=true
# 指定 PostgreSQL 的方言
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
# 1h in millisecond
security.jwt.expiration-time=3600000
